version: '3'

services:
  flask:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - flask
